=== cerbos/cerbos/schema/jsonschema/cerbos/engine/v1/PlanResourcesInput.schema.json
{
  "$id": "https://api.cerbos.dev/cerbos/engine/v1/PlanResourcesInput.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "cerbos.engine.v1.AuxData": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "jwt": {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/definitions/google.protobuf.Value"
          }
        }
      }
    },
    "cerbos.engine.v1.PlanResourcesInput.Resource": {
      "type": "object",
      "required": [
        "kind"
      ],
      "additionalProperties": false,
      "properties": {
        "attr": {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/definitions/google.protobuf.Value"
          }
        },
        "kind": {
          "type": "string",
          "minLength": 1
        },
        "policyVersion": {
          "type": "string",
          "pattern": "^[0-9A-Z_a-z]*$"
        },
        "scope": {
          "type": "string",
          "pattern": "^([0-9A-Za-z][\\-0-9A-Z_a-z]*(\\.[\\-0-9A-Z_a-z]*)*)*$"
        },
        "scopes": {
          "type": "array",
          "items": {
            "type": "string",
            "minLength": 0
          },
          "minItems": 0,
          "uniqueItems": true
        }
      }
    },
    "cerbos.engine.v1.Principal": {
      "type": "object",
      "required": [
        "id",
        "roles"
      ],
      "additionalProperties": false,
      "properties": {
        "attr": {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/definitions/google.protobuf.Value"
          },
          "propertyNames": {
            "type": "string",
            "minLength": 1
          }
        },
        "id": {
          "type": "string",
          "minLength": 1
        },
        "policyVersion": {
          "type": "string",
          "pattern": "^[0-9A-Z_a-z]*$"
        },
        "roles": {
          "type": "array",
          "items": {
            "type": "string",
            "minLength": 1
          },
          "minItems": 1,
          "uniqueItems": true
        },
        "scope": {
          "type": "string",
          "pattern": "^([0-9A-Za-z][\\-0-9A-Z_a-z]*(\\.[\\-0-9A-Z_a-z]*)*)*$"
        }
      }
    },
    "google.protobuf.Value": {
      "title": "Value",
      "description": "A dynamically-typed value."
    }
  },
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "action": {
      "type": "string"
    },
    "auxData": {
      "$ref": "#/definitions/cerbos.engine.v1.AuxData"
    },
    "includeMeta": {
      "type": "boolean"
    },
    "principal": {
      "$ref": "#/definitions/cerbos.engine.v1.Principal"
    },
    "requestId": {
      "type": "string"
    },
    "resource": {
      "$ref": "#/definitions/cerbos.engine.v1.PlanResourcesInput.Resource"
    }
  }
}

=== cerbos/cerbos/hack/dev/requests/x_scope_plan_resources/req2.json
{
  "requestId": "test",
  "includeMeta": true,
  "action": "approve",
  "principal": {
    "id": "maggie",
    "policyVersion": "20210210",
    "roles": [
      "manager"
    ],
    "attr": {
      "reader": false,
      "department": "marketing",
      "managed_geographies": "GB",
      "geography": "GB",
      "team": "design"
    }
  },
  "resource": {
    "kind": "leave_request",
    "policyVersion": "20210210",
    "scopes": ["abc", "def"],
    "attr": {
      "geography": "GB"
    }
  },
  "auxData": {
    "jwt": {
      "token": "eyJhbGciOiJFUzM4NCIsImtpZCI6IjE5TGZaYXRFZGc4M1lOYzVyMjNndU1KcXJuND0iLCJ0eXAiOiJKV1QifQ.eyJhdWQiOlsiY2VyYm9zLWp3dC10ZXN0cyJdLCJjdXN0b21BcnJheSI6WyJBIiwiQiIsIkMiXSwiY3VzdG9tSW50Ijo0MiwiY3VzdG9tTWFwIjp7IkEiOiJBQSIsIkIiOiJCQiIsIkMiOiJDQyJ9LCJjdXN0b21TdHJpbmciOiJmb29iYXIiLCJleHAiOjE5NDk5MzQwMzksImlzcyI6ImNlcmJvcy10ZXN0LXN1aXRlIn0.WN_tOScSpd_EI-P5EI1YlagxEgExSfBjAtcrgcF6lyWj1lGpR_GKx9goZEp2p_t5AVWXN_bjz_sMUmJdJa4cVd55Qm1miR-FKu6oNRHnSEWdMFmnArwPw-YDJWfylLFX"
    }
  }
}

=== cerbos/cerbos/hack/dev/requests/plan_resources/req5.json
{
  "requestId": "test",
  "includeMeta": true,
  "action": "delete",
  "principal": {
    "id": "john",
    "roles": [
      "employee"
    ],
    "attr": {
      "department": "marketing",
      "managed_geographies": "GB",
      "geography": "GB",
      "team": "design",
      "ip_address": "10.20.0.5"
    }
  },
  "resource": {
    "kind": "leave_request",
    "scope": "acme.hr.uk",
    "attr": {
      "geography": "GB"
    }
  },
  "auxData": {
    "jwt": {
      "token": "eyJhbGciOiJFUzM4NCIsImtpZCI6IjE5TGZaYXRFZGc4M1lOYzVyMjNndU1KcXJuND0iLCJ0eXAiOiJKV1QifQ.eyJhdWQiOlsiY2VyYm9zLWp3dC10ZXN0cyJdLCJjdXN0b21BcnJheSI6WyJBIiwiQiIsIkMiXSwiY3VzdG9tSW50Ijo0MiwiY3VzdG9tTWFwIjp7IkEiOiJBQSIsIkIiOiJCQiIsIkMiOiJDQyJ9LCJjdXN0b21TdHJpbmciOiJmb29iYXIiLCJleHAiOjE5NDk5MzQwMzksImlzcyI6ImNlcmJvcy10ZXN0LXN1aXRlIn0.WN_tOScSpd_EI-P5EI1YlagxEgExSfBjAtcrgcF6lyWj1lGpR_GKx9goZEp2p_t5AVWXN_bjz_sMUmJdJa4cVd55Qm1miR-FKu6oNRHnSEWdMFmnArwPw-YDJWfylLFX"
    }
  }
}

=== cerbos/cerbos/hack/dev/requests/plan_resources/req2.json
{
  "requestId":  "test",
  "includeMeta": true,
  "action": "defer",
  "principal":  {
    "id":  "harry",
    "policyVersion":  "20210210",
    "attr": {
      "reader": false
    },
    "roles":  [
      "employee"
    ]
  },
  "resource": {
    "kind": "leave_request",
    "policyVersion":  "20210210"
  },
  "auxData": {
    "jwt": {
      "token": "eyJhbGciOiJFUzM4NCIsImtpZCI6IjE5TGZaYXRFZGc4M1lOYzVyMjNndU1KcXJuND0iLCJ0eXAiOiJKV1QifQ.eyJhdWQiOlsiY2VyYm9zLWp3dC10ZXN0cyJdLCJjdXN0b21BcnJheSI6WyJBIiwiQiIsIkMiXSwiY3VzdG9tSW50Ijo0MiwiY3VzdG9tTWFwIjp7IkEiOiJBQSIsIkIiOiJCQiIsIkMiOiJDQyJ9LCJjdXN0b21TdHJpbmciOiJmb29iYXIiLCJleHAiOjE5NDk5MzQwMzksImlzcyI6ImNlcmJvcy10ZXN0LXN1aXRlIn0.WN_tOScSpd_EI-P5EI1YlagxEgExSfBjAtcrgcF6lyWj1lGpR_GKx9goZEp2p_t5AVWXN_bjz_sMUmJdJa4cVd55Qm1miR-FKu6oNRHnSEWdMFmnArwPw-YDJWfylLFX"
    }
  }
}
