=== cerbos/cerbos/schema/jsonschema/cerbos/request/v1/CheckResourceSetRequest.schema.json
{
  "$id": "https://api.cerbos.dev/cerbos/request/v1/CheckResourceSetRequest.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "cerbos.engine.v1.Principal": {
      "type": "object",
      "required": [
        "id",
        "roles"
      ],
      "additionalProperties": false,
      "properties": {
        "attr": {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/definitions/google.protobuf.Value"
          }
        },
        "id": {
          "type": "string",
          "minLength": 1
        },
        "policyVersion": {
          "type": "string",
          "pattern": "^[[:word:]]*$"
        },
        "roles": {
          "type": "array",
          "items": {
            "type": "string",
            "pattern": "^[[:word:]\\-\\.]+$"
          },
          "maxItems": 20,
          "minItems": 1,
          "uniqueItems": true
        },
        "scope": {
          "type": "string",
          "pattern": "^([[:alpha:]][[:word:]\\-]+(\\.[[:alpha:]][[:word:]\\-]*)*)*$"
        }
      }
    },
    "cerbos.request.v1.AttributesMap": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "attr": {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/definitions/google.protobuf.Value"
          }
        }
      }
    },
    "cerbos.request.v1.AuxData": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "jwt": {
          "$ref": "#/definitions/cerbos.request.v1.AuxData.JWT"
        }
      }
    },
    "cerbos.request.v1.AuxData.JWT": {
      "type": "object",
      "required": [
        "token"
      ],
      "additionalProperties": false,
      "properties": {
        "keySetId": {
          "type": "string"
        },
        "token": {
          "type": "string",
          "minLength": 1
        }
      }
    },
    "cerbos.request.v1.ResourceSet": {
      "type": "object",
      "required": [
        "kind",
        "instances"
      ],
      "additionalProperties": false,
      "properties": {
        "instances": {
          "type": "object",
          "maxProperties": 20,
          "minProperties": 1,
          "additionalProperties": {
            "$ref": "#/definitions/cerbos.request.v1.AttributesMap"
          }
        },
        "kind": {
          "type": "string",
          "minLength": 1,
          "pattern": "^[[:alpha:]][[:word:]\\@\\.\\-/]*(\\:[[:alpha:]][[:word:]\\@\\.\\-/]*)*$"
        },
        "policyVersion": {
          "type": "string",
          "pattern": "^[[:word:]]*$"
        },
        "scope": {
          "type": "string",
          "pattern": "^([[:alpha:]][[:word:]\\-]+(\\.[[:alpha:]][[:word:]\\-]*)*)*$"
        }
      }
    },
    "google.protobuf.Value": {
      "title": "Value",
      "description": "A dynamically-typed value."
    }
  },
  "type": "object",
  "required": [
    "actions",
    "principal",
    "resource"
  ],
  "additionalProperties": false,
  "properties": {
    "actions": {
      "type": "array",
      "items": {
        "type": "string",
        "minLength": 1
      },
      "maxItems": 10,
      "minItems": 1,
      "uniqueItems": true
    },
    "auxData": {
      "$ref": "#/definitions/cerbos.request.v1.AuxData"
    },
    "includeMeta": {
      "type": "boolean"
    },
    "principal": {
      "$ref": "#/definitions/cerbos.engine.v1.Principal"
    },
    "requestId": {
      "type": "string"
    },
    "resource": {
      "$ref": "#/definitions/cerbos.request.v1.ResourceSet"
    }
  }
}

=== cerbos/cerbos/hack/dev/requests/check_resource_set/resource_set.json
{
  "requestId":  "test",
  "includeMeta": true,
  "actions":  [
    "view:public",
    "approve",
    "create",
    "defer"
  ],
  "principal":  {
    "id":  "donald_duck",
    "policyVersion":  "20210210",
    "roles":  [
      "employee"
    ],
    "attr":  {
      "department":  "marketing",
      "geography":  "GB",
      "team":  "design"
    }
  },
  "resource":  {
    "kind":  "leave_request",
    "policyVersion":  "20210210",
    "instances":  {
      "XX125":  {
        "attr":  {
          "department":  "marketing",
          "geography":  "GB",
          "id":  "XX125",
          "owner":  "john",
          "team":  "design"
        }
      },
      "XX150":  {
        "attr":  {
          "department":  "marketing",
          "geography":  "GB",
          "id":  "XX150",
          "owner":  "mary",
          "team":  "design"
        }
      },
      "XX250":  {
        "attr":  {
          "department":  "marketing",
          "geography":  "GB",
          "id":  "XX250",
          "owner":  "xenia",
          "team":  "design"
        }
      },
      "YY100":  {
        "attr":  {
          "department":  "marketing",
          "dev_record":  true,
          "geography":  "US",
          "id":  "YY100",
          "owner":  "zach",
          "team":  "comms"
        }
      },
      "YY200":  {
        "attr":  {
          "department":  "engineering",
          "dev_record":  true,
          "geography":  "GB",
          "id":  "YY200",
          "owner":  "christa",
          "team":  "cloud"
        }
      }
    }
  },
  "auxData": {
    "jwt": {
      "token": "eyJhbGciOiJFUzM4NCIsImtpZCI6IjE5TGZaYXRFZGc4M1lOYzVyMjNndU1KcXJuND0iLCJ0eXAiOiJKV1QifQ.eyJhdWQiOlsiY2VyYm9zLWp3dC10ZXN0cyJdLCJjdXN0b21BcnJheSI6WyJBIiwiQiIsIkMiXSwiY3VzdG9tSW50Ijo0MiwiY3VzdG9tTWFwIjp7IkEiOiJBQSIsIkIiOiJCQiIsIkMiOiJDQyJ9LCJjdXN0b21TdHJpbmciOiJmb29iYXIiLCJleHAiOjE5NDk5MzQwMzksImlzcyI6ImNlcmJvcy10ZXN0LXN1aXRlIn0.WN_tOScSpd_EI-P5EI1YlagxEgExSfBjAtcrgcF6lyWj1lGpR_GKx9goZEp2p_t5AVWXN_bjz_sMUmJdJa4cVd55Qm1miR-FKu6oNRHnSEWdMFmnArwPw-YDJWfylLFX"
    }
  }
}

=== cerbos/cerbos/hack/dev/requests/check_resource_set/req02.json
{
  "requestId": "test",
  "includeMeta": true,
  "actions": [
    "view:public",
    "delete",
    "approve"
  ],
  "principal": {
    "id": "john",
    "roles": [
      "employee"
    ],
    "attr": {
      "department": "marketing",
      "geography": "GB",
      "team": "design",
      "ip_address": "10.20.0.5"
    }
  },
  "resource": {
    "kind": "leave_request",
    "scope": "acme.hr.uk",
    "instances": {
      "XX125": {
        "attr": {
          "department": "marketing",
          "geography": "GB",
          "id": "XX125",
          "owner": "john",
          "team": "design"
        }
      }
    }
  }
}

=== cerbos/cerbos/hack/loadtest/ghz/crs_req01.json
{
  "requestId": "{{ .UUID }}",
  "actions": [
    "view:public",
    "approve"
  ],
  "principal": {
    "id": "john",
    "policyVersion": "20210210",
    "roles": [
      "employee"
    ],
    "attr": {
      "department": "marketing",
      "geography": "GB",
      "team": "design"
    }
  },
  "resource": {
    "kind": "{{ randomInt 0 1000 | printf `leave_request_%05d` }}",
    "policyVersion": "20210210",
    "instances": {
      "XX125": {
        "attr": {
          "department": "marketing",
          "geography": "GB",
          "id": "XX125",
          "owner": "john",
          "team": "design"
        }
      }
    }
  }
}
