=== cerbos/cerbos/schema/jsonschema/authzen/authorization/v1/AccessEvaluationBatchRequest.schema.json
{
  "$id": "https://api.cerbos.dev/authzen/authorization/v1/AccessEvaluationBatchRequest.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "authzen.authorization.v1.AccessEvaluationBatchRequest.Evaluation": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "action": {
          "$ref": "#/definitions/authzen.authorization.v1.Action"
        },
        "context": {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/definitions/google.protobuf.Value"
          },
          "propertyNames": {
            "type": "string",
            "minLength": 1
          }
        },
        "resource": {
          "$ref": "#/definitions/authzen.authorization.v1.Resource"
        },
        "subject": {
          "$ref": "#/definitions/authzen.authorization.v1.Subject"
        }
      }
    },
    "authzen.authorization.v1.Action": {
      "type": "object",
      "required": [
        "name"
      ],
      "additionalProperties": false,
      "properties": {
        "name": {
          "type": "string",
          "minLength": 1
        },
        "properties": {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/definitions/google.protobuf.Value"
          },
          "propertyNames": {
            "type": "string",
            "minLength": 1
          }
        }
      }
    },
    "authzen.authorization.v1.Resource": {
      "type": "object",
      "required": [
        "type",
        "id"
      ],
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "string",
          "minLength": 1
        },
        "properties": {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/definitions/google.protobuf.Value"
          },
          "propertyNames": {
            "type": "string",
            "minLength": 1
          }
        },
        "type": {
          "type": "string",
          "minLength": 1
        }
      }
    },
    "authzen.authorization.v1.Subject": {
      "type": "object",
      "required": [
        "type",
        "id"
      ],
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "string",
          "minLength": 1
        },
        "properties": {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/definitions/google.protobuf.Value"
          },
          "propertyNames": {
            "type": "string",
            "minLength": 1
          }
        },
        "type": {
          "type": "string",
          "minLength": 1
        }
      }
    },
    "google.protobuf.Value": {
      "title": "Value",
      "description": "A dynamically-typed value."
    }
  },
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "action": {
      "$ref": "#/definitions/authzen.authorization.v1.Action"
    },
    "context": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#/definitions/google.protobuf.Value"
      },
      "propertyNames": {
        "type": "string",
        "minLength": 1
      }
    },
    "evaluations": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/authzen.authorization.v1.AccessEvaluationBatchRequest.Evaluation"
      },
      "minItems": 1
    },
    "resource": {
      "$ref": "#/definitions/authzen.authorization.v1.Resource"
    },
    "subject": {
      "$ref": "#/definitions/authzen.authorization.v1.Subject"
    }
  }
}

=== cerbos/cerbos/hack/dev/requests/access_evaluation/req02_XX125_delete.json
{
  "subject": {
    "type": "user",
    "id": "john",
    "properties": {
      "cerbos.scope": "acme.hr",
      "cerbos.roles": [
        "employee"
      ],
      "department": "marketing",
      "geography": "GB",
      "team": "design",
      "ip_address": "10.20.5.5"
    }
  },
  "resource": {
    "type": "leave_request",
    "id": "XX125",
    "properties": {
      "cerbos.scope": "acme.hr.uk",
      "department": "marketing",
      "geography": "GB",
      "id": "XX125",
      "owner": "john",
      "team": "design"
    }
  },
  "action": {
    "name": "delete",
    "properties": {}
  },
  "context": {
    "cerbos.requestId": "test"
  }
}

=== cerbos/cerbos/hack/dev/requests/access_evaluation/req03_XX125_view_public.json
{
  "subject": {
    "type": "user",
    "id": "employee1",
    "properties": {
      "cerbos.roles": [
        "employee"
      ],
      "department": "marketing",
      "geography": "GB",
      "team": "design"
    }
  },
  "resource": {
    "type": "equipment_request",
    "id": "XX125",
    "properties": {
      "id": "XX125"
    }
  },
  "action": {
    "name": "view:public",
    "properties": {}
  },
  "context": {
    "cerbos.requestId": "test",
    "cerbos.includeMeta": true
  }
}

=== cerbos/cerbos/hack/dev/requests/access_evaluation/req02_XX225_create.json
{
  "subject": {
    "type": "user",
    "id": "john",
    "properties": {
      "cerbos.scope": "acme.hr",
      "cerbos.roles": [
        "employee"
      ],
      "department": "marketing",
      "geography": "GB",
      "team": "design",
      "ip_address": "10.20.5.5"
    }
  },
  "resource": {
    "type": "leave_request",
    "id": "XX225",
    "properties": {
      "cerbos.scope": "acme.hr",
      "department": "marketing",
      "geography": "GB",
      "id": "XX225",
      "owner": "john",
      "team": "design"
    }
  },
  "action": {
    "name": "create",
    "properties": {}
  },
  "context": {
    "cerbos.requestId": "test",
    "cerbos.includeMeta": true
  }
}
